"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

[aws]
disabled = true

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "
disabled = true

[erlang]
symbol = "ⓔ "

[nodejs]
symbol = "[⬢](bold green) "

[pulumi]
symbol = "🧊 "

[typst]
symbol = "t "

# https://starship.rs/config/#package-version
[package]
disabled = true

# # https://starship.rs/config/#character
# Replace the '❯' symbol in the prompt with '➜'
[kubernetes]
symbol = "⎈ "
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false

[[kubernetes.contexts]]
context_pattern = ".*prod.*"
context_alias = "prod"
style = "bold red"

[[kubernetes.contexts]]
context_pattern = ".*staging.*"
context_alias = "staging"
style = "bold yellow"

[[kubernetes.contexts]]
context_pattern = ".*dev.*"
context_alias = "dev"
style = "bold green"

[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[❯](bold red)"