"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
format = "$directory$git_branch$git_status$python$cmd_duration$line_break$character"

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = " [$branch]($style)"
style = "bold purple"

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "bold yellow"

[cmd_duration]
min_time = 2000
format = " took [$duration]($style)"
style = "bold yellow"

[python]
format = ' [($virtualenv)]($style)'
style = "bold green"

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[❯](bold red)"

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

[package]
disabled = true
